Repository wrj95/TCC, pull requests merged in 2018-10, with the labels that each got.

#12 validation about Error password or email return to Login and error Su…
  .gitignore
  Back_End/Dockerfile
  Back_End/Paginas/Emissao.html
  Back_End/Paginas/Solicitacao.html
  Back_End/README.md
  Back_End/Utils/Dump.txt
  Back_End/api/models/companyDAO.js
  Back_End/api/models/userDAO.js
  Back_End/api/routes/authentication.js
  Back_End/api/routes/company.js
  Back_End/api/routes/helloWorld.js
  Back_End/api/routes/users.js
  Back_End/app.js
  Back_End/config/database.js
  Back_End/npm-shrinkwrap.json
  Back_End/package.json
  DB/DBDump.sql
  Front_End/LoginEmp.html
  Front_End/cadastro.html
  Front_End/css/backgroundSite.jpg
  Front_End/css/style.css
  Front_End/empresa.html
  Front_End/js/LoginCompany.js
  Front_End/js/LoginUser.js
  Front_End/js/validatorCadastro.js
  Front_End/js/validatorEmpresa.js
  README.md
  docker-compose.yml
Labels: Task, bug, invalid

#13 State, City and Address to Company User implemented
  Back_End/Pages/Emissao.ejs
  Back_End/Pages/Solicitacao.ejs
  Back_End/api/routes/authentication.js
  DB/DBDump.sql
  Front_End/Dados/estados_cidades.json
  Front_End/Dockerfile
  Front_End/cadastro.html
  Front_End/empresa.html
  Front_End/js/LoginCompany.js
  Front_End/js/validatorCadastro.js
  Front_End/js/validatorEmpresa.js
Labels: Problem, Task, bug

#14 V api 0.3.1
  Back_End/api/routes/authentication.js
  Back_End/api/routes/company.js
  Back_End/api/routes/helloWorld.js
  Back_End/api/routes/users.js
  Back_End/api/views/Emissao.ejs
  Back_End/api/views/Solicitacao.ejs
  Back_End/app.js
  Back_End/config/middleware.js
  Back_End/npm-shrinkwrap.json
  Back_End/package.json
  DB/DBDump.sql
  Front_End/js/LoginCompany.js
  Front_End/js/LoginUser.js
  docker-compose.yml
Labels: Task, bugFix

#15 V api 0.3.1
  Back_End/api/models/userDAO.js
  Back_End/api/routes/company.js
  Back_End/api/routes/helloWorld.js
  Back_End/api/routes/users.js
  Back_End/api/views/emissao.ejs
  Back_End/api/views/solicitacao.ejs
  Back_End/app.js
  Back_End/config/errorhandler.js
  Back_End/config/server.js
Labels: Task

#18 I did some Select and Insert that we'll use in app
  Back_End/api/models/companyDAO.js
  Back_End/api/models/userDAO.js
Labels: Database, Task

#20 Register Address to User and COmpany contacts and others stuffs
  Back_End/api/views/Company/ContatosEmpresa.ejs
  Back_End/api/views/Company/MeusOrcamentos.ejs
  Back_End/api/views/Company/emissao.ejs
  Back_End/api/views/Company/js/validateContactCompany.js
  Back_End/api/views/Company/js/validateRespond.js
  Back_End/api/views/User/Enderecos.ejs
  Back_End/api/views/User/js/AddressUser.js
  Back_End/api/views/User/js/validateRequest.js
  Back_End/api/views/User/solicitacao.ejs
  Back_End/api/views/js/Mascaras.js
Labels: Task

#24 V api 0.8.2
  Back_End/api/routes/users.js
Labels: bugFix
