Repository wrj95/TCC, pull requests merged in 2018-11, with the labels that each got.

#29 V api 0.10.0
  Back_End/Utils/Dump.txt
  Back_End/api/models/companyDAO.js
  Back_End/api/routes/authentication.js
  Back_End/api/routes/company.js
  Back_End/api/views/company/detailsOrcamento.ejs
  Back_End/api/views/company/emissao.ejs
  Back_End/api/views/company/feedOrcamento.ejs
  Back_End/api/views/user/minhasSolicitacoes.ejs
  Back_End/api/views/user/solicitacao.ejs
  Back_End/config/middleware.js
  Back_End/config/server.js
  DB/DBDump.sql
  Front_End/js/LoginCompany.js
  Front_End/js/validatorEmpresa.js
Labels: Task

#31 V api 0.12.0
  Back_End/api/models/userDAO.js
  Back_End/api/routes/users.js
  Back_End/api/views/user/detalheResposta.ejs
  Back_End/api/views/user/respostas.ejs
  Back_End/api/views/user/solicitacao.ejs
  DB/DBDump.sql
Labels: Task

#30 V api 0.11.0
  Back_End/config/middleware.js
Labels: bugFix

#37 Orcamentos historic to Company implemented
  Back_End/api/models/companyDAO.js
  Back_End/api/routes/company.js
  Back_End/api/views/company/detalheOrcamento.ejs
  Back_End/api/views/company/feedOrcamento.ejs
  Back_End/api/views/company/meusOrcamentos.ejs
Labels: Task

#39 Dev
  Back_End/api/models/companyDAO.js
  Back_End/api/models/generalDAO.js
  Back_End/api/models/userDAO.js
  Back_End/api/routes/authentication.js
  Back_End/api/routes/company.js
  Back_End/api/routes/general.js
  Back_End/api/routes/users.js
  Back_End/api/views/company/detalheOrcamento.ejs
  Back_End/api/views/company/feedOrcamento.ejs
  Back_End/api/views/company/meusOrcamentos.ejs
  Back_End/api/views/user/detalheSolicitacao.ejs
  Back_End/api/views/user/enderecos.ejs
  Back_End/api/views/user/minhasSolicitacoes.ejs
  Back_End/api/views/user/respostas.ejs
  Back_End/api/views/user/solicitacao.ejs
  Back_End/config/middleware.js
  Back_End/config/server.js
  DB/DBDump.sql
  Front_End/js/validatorEmpresa.js
Labels: Task

#40 V api 0.13.0
  Back_End/api/models/userDAO.js
  Back_End/api/routes/authentication.js
  Back_End/api/routes/company.js
  Back_End/api/routes/helloWorld.js
  Back_End/api/routes/users.js
  Back_End/api/views/company/aprovados.ejs
  Back_End/api/views/company/detailsOrcamento.ejs
  Back_End/api/views/company/detalheAprovacao.ejs
  Back_End/api/views/company/detalheOrcamento.ejs
  Back_End/api/views/company/emissao.ejs
  Back_End/api/views/company/feedOrcamento.ejs
  Back_End/api/views/company/meusOrcamentos.ejs
  Back_End/api/views/css/notfound.png
  Back_End/api/views/general/notfoundpage.ejs
  Back_End/api/views/js/mascaras.js
  Back_End/api/views/user/detalheResposta.ejs
  Back_End/api/views/user/detalheSolicitacao.ejs
  Back_End/api/views/user/enderecos.ejs
  Back_End/api/views/user/js/addressUser.js
  Back_End/api/views/user/js/validateRequest.js
  Back_End/api/views/user/minhasSolicitacoes.ejs
  Back_End/api/views/user/respostas.ejs
  Back_End/api/views/user/solicitacao.ejs
  Back_End/config/errorhandler.js
  Back_End/config/middleware.js
  Back_End/config/middlewares.js
  Back_End/config/server.js
  Back_End/config/strategy.js
  Back_End/npm-shrinkwrap.json
  Back_End/package.json
  Front_End/index.html
  Front_End/js/LoginCompany.js
  Front_End/js/LoginUser.js
  docker-compose.yml
Labels: bugFix, enhancement

#43 V api 0.19.0
  Back_End/Utils/backupDump.sh
  Back_End/Utils/restoreDump.sh
  Back_End/api/routes/authentication.js
  DB/DBDump.sql
Labels: enhancement

#46 Adjusts about Answer a Solicitacao and approve that Solicitacao
  Back_End/api/models/userDAO.js
  Back_End/api/routes/users.js
  Back_End/api/views/company/detalheSolicitacao.ejs
  Back_End/api/views/company/emissao.ejs
  Back_End/api/views/company/feedOrcamento.ejs
  Back_End/api/views/user/detalheResposta.ejs
Labels: bug, bugFix

#47 Adjust other bugs and I fixed Company login
  Back_End/api/models/companyDAO.js
  Back_End/api/models/userDAO.js
  Back_End/api/routes/authentication.js
  Back_End/api/routes/company.js
  Back_End/api/views/company/detalheAprovacao.ejs
  Back_End/api/views/user/detalheResposta.ejs
  Back_End/config/strategy.js
  DB/DBDump.sql
  Front_End/LoginEmp.html
  Front_End/cadastro.html
  Front_End/empresa.html
  Front_End/js/LoginCompany.js
  Front_End/js/validatorCadastro.js
  Front_End/js/validatorEmpresa.js
Labels: bug, bugFix
